*: fix staticcheck problems
archiver.go:262:86: argument err is overwritten before first use (SA4009)
archiver.go:440:24: should use time.Since instead of time.Now().Sub (S1012)
archiver.go:470:33: should use time.Since instead of time.Now().Sub (S1012)
archiver.go:477:32: should use time.Since instead of time.Now().Sub (S1012)
archiver.go:486:17: should use time.Since instead of time.Now().Sub (S1012)
archiver.go:492:16: should use time.Since instead of time.Now().Sub (S1012)
archiver_test.go:206:8: this value of err is never used (SA4006)
changes.go:19:2: only the first constant in this group has an explicit type (SA9004)
cli/borges-tool/queue.go:27:2: field fs is unused (U1000)
cli/borges/producer.go:96:20: error strings should not be capitalized (ST1005)
consumer.go:19:2: field running is unused (U1000)
executor_test.go:20:2: field p is unused (U1000)
linejobiter_test.go:88:2: this value of j is never used (SA4006)
linejobiter_test.go:109:2: this value of j is never used (SA4006)
producer_test.go:75:8: this value of err is never used (SA4006)
producer_test.go:97:8: this value of err is never used (SA4006)
producer_test.go:136:8: this value of err is never used (SA4006)
storage/database_test.go:40:2: this value of repo is never used (SA4006)
storage/local_test.go:36:2: this value of repo is never used (SA4006)

Signed-off-by: Javi Fontan <jfontan@gmail.com>